# Generated by Django 3.1.6 on 2021-02-24 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('view', models.IntegerField(default=0)),
                ('publish_date', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(default='sale', max_length=25)),
                ('size', models.IntegerField()),
                ('imageurl', models.TextField(default='https://gomushin.s3.ap-northeast-2.amazonaws.com/jordan/p_11cedf5899e0415e9cd88df144cae4ee.png', max_length=500)),
                ('sell_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['title', 'content'], name='app_item_title_929083_idx'),
        ),
    ]
