# Generated by Django 3.1.6 on 2021-02-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210224_0930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
