# Generated by Django 3.1.5 on 2021-02-07 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_buyreservation_buysell_item_wanteditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wanteditem',
            name='username',
        ),
        migrations.AddField(
            model_name='wanteditem',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
