# Generated by Django 3.1.6 on 2021-02-14 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_buyreservation_buysell_item_wanteditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.TextField(default='https://gomushin.s3.ap-northeast-2.amazonaws.com/jordan/p_11cedf5899e0415e9cd88df144cae4ee.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='publish_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='wanteditem',
            name='username',
        ),
        migrations.AddField(
            model_name='wanteditem',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
