# Generated by Django 3.1.6 on 2021-02-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
