# Generated by Django 3.1.6 on 2021-02-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
