# Generated by Django 3.1.6 on 2021-02-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_fulltesttest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FulltestTest',
        ),
    ]
