node {
    stage('SCM Checkout'){
        git branch: 'feat-BE-TestCode', credentialsId: 'koozzi', url: 'https://github.com/Koozzi/black-gomushin'
    }
    
    stage('Docker Build'){
        sh '''
            cd back 
            docker build -t koozzi666/dev-gomushin-back .
        '''
    }
    
    stage('Push image') {
        withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'USER', passwordVariable: 'PASSWORD')]) {
            sh "docker login -u $USER -p $PASSWORD"
            sh "docker push koozzi666/dev-gomushin-back"
        }
    }

    stage('Run container') {
        sh "docker rm -f dev-gomushin-back | true"
        sh "docker pull koozzi666/dev-gomushin-back"
        withCredentials([string(credentialsId: 'gomushin-db', variable: 'DB_PASSWORD')]) {
            sh "docker run --name dev-gomushin-back -tid -e PASSWORD=$DB_PASSWORD -p 8000:8000 koozzi666/dev-gomushin-back"
        }
    }

    stage('Test'){
        environment {
            KOOZZI_TOKEN = credentials('KOOZZI_TOKEN')
        }

        sh '''
        export KOOZZI_TOKEN=$KOOZZI_TOKEN
        cd back && cd api_test
        python3 api_test_item.py
        python3 api_test_user.py
        '''
    }

    stage('Docker Deploy'){
        sshagent(credentials: ['ssh-backend']) {
            sh "ssh -o StrictHostKeyChecking=no ubuntu@10.0.0.79 sudo docker rm -f dev-gomushin-back | true"
            sh "ssh -o StrictHostKeyChecking=no ubuntu@10.0.0.79 sudo docker pull koozzi666/dev-gomushin-back"
            withCredentials([string(credentialsId: 'gomushin-db', variable: 'DB_PASSWORD')]) {
                sh "ssh -o StrictHostKeyChecking=no ubuntu@10.0.0.79 sudo docker run --name dev-gomushin-back -tid -e PASSWORD=$DB_PASSWORD -p 8000:8000 koozzi666/dev-gomushin-back"
            }
        }
    }
}